language: bash
sudo: required

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.25.5
    - DOCKER_ENGINE_VERSION=19.03.8
    - COMPOSE_FILES="-f docker-compose.yml"

before_install:
  - docker build -t name/aaa -f Docckerfile.dev .
script:
  - docker run name/aaa
