version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - '.:/app/'
    environment:
    - FLASK_APP=run.py
  tests:
    container_name: docker_flask_test
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
    command: bash test.sh