version: '3'
services:
  web:
    image: atsushiiii/multi-server
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash entrypoint.sh
    expose:
      - 5000
  nginx:
    restart: always
    image: atsushiiii/multi-nginx
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web